library(data.table)
temp <- tempfile()
download.file("https://d396qusza40orc.cloudfront.net/exdata%2Fdata%2Fhousehold_power_consumption.zip",temp)
data <- fread(unzip(temp, files = "household_power_consumption.txt"),na.strings = "?")
rm(temp)
data$DateTime <- paste(data$Date, data$Time)
data$Date <- as.Date(data$Date, "%d/%m/%Y")
subData<-data[data$Date==as.Date("2007-02-01") | data$Date==as.Date("2007-02-02"),]

png(filename = "plot4.png", width = 480, height = 480, units = "px")
par(mfrow = c(2,2))
plot(strptime(subData$DateTime, format = "%d/%m/%Y %H:%M:%S"),subData$Global_active_power,type = "l",xlab="",ylab = "Gobal Active Power (kilowatts)")
plot(strptime(subData$DateTime, format = "%d/%m/%Y %H:%M:%S"),subData$Voltage ,type = "l",xlab="datetime",ylab = "Voltage")
plot(strptime(subData$DateTime, format = "%d/%m/%Y %H:%M:%S"),subData$Sub_metering_1,type = "l",xlab = "", ylab = "Energy sub metering",col = "grey")
points(strptime(subData$DateTime, format = "%d/%m/%Y %H:%M:%S"),subData$Sub_metering_2,type = "l",col = "red")
points(strptime(subData$DateTime, format = "%d/%m/%Y %H:%M:%S"),subData$Sub_metering_3,type = "l",col = "blue")
legend("topright", lty=c(1,1),col = c("grey","red","blue"), legend = c("Sub_metering_1","Sub_metering_2","Sub_metering_3"))
plot(strptime(subData$DateTime, format = "%d/%m/%Y %H:%M:%S"),subData$Global_reactive_power,type = "l",xlab="datetime",ylab = "Gobal_reactive_power")

dev.off()
